name: quspin
channels:
  - weinbe58
  - pyviz/label/dev
  - defaults
dependencies:
  - asn1crypto=0.24.0=py36_0
  - attrs=19.1.0=py36_1
  - backcall=0.1.0=py36_0
  - blas=1.0=mkl
  - bleach=3.1.0=py36_0
  - bokeh=1.2.0=py36_0
  - bzip2=1.0.6=h14c3975_5
  - ca-certificates=2019.5.15=0
  - cairo=1.14.12=h7636065_2
  - cartopy=0.16.0=py36hfa13621_0
  - certifi=2019.3.9=py36_0
  - cffi=1.12.3=py36h2e261b9_0
  - cftime=1.0.3.4=py36hdd07704_1
  - chardet=3.0.4=py36_1
  - click=7.0=py36_0
  - click-plugins=1.1.1=py_0
  - cligj=0.5.0=py36_0
  - cloudpickle=1.1.1=py_0
  - colorcet=2.0.1=py_0
  - cryptography=2.3.1=py36hc365091_0
  - curl=7.61.0=h84994c4_0
  - cycler=0.10.0=py36_0
  - cytoolz=0.9.0.1=py36h14c3975_1
  - dask=1.2.2=py_0
  - dask-core=1.2.2=py_0
  - datashader=0.7.0=py_0
  - datashape=0.5.4=py36_1
  - dbus=1.13.6=h746ee38_0
  - decorator=4.4.0=py36_1
  - defusedxml=0.6.0=py_0
  - descartes=1.1.0=py36_0
  - dill=0.2.9=py36_0
  - distributed=1.28.1=py36_0
  - entrypoints=0.3=py36_0
  - expat=2.2.6=he6710b0_0
  - fastparquet=0.3.0=py36hdd07704_0
  - fiona=1.7.12=py36h3f37509_0
  - fontconfig=2.12.6=h49f89f6_0
  - freetype=2.8=hab7d2ae_1
  - freexl=1.0.5=h14c3975_0
  - gdal=2.2.2=py36hc209d97_1
  - geopandas=0.4.1=py_0
  - geos=3.6.2=heeff764_2
  - geoviews=1.6.3a2=py_0
  - geoviews-core=1.6.3a2=py_0
  - giflib=5.1.4=h14c3975_1
  - glib=2.56.2=hd408876_0
  - gmp=6.1.2=h6c8ec71_1
  - gmpy2=2.0.8=py36h10f8cd9_2
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - hdf4=4.2.13=h3ca952b_2
  - hdf5=1.10.2=hba1933b_1
  - heapdict=1.0.0=py36_2
  - holoviews=1.12.3=py_0
  - hvplot=0.4.0=py_0
  - icu=58.2=h9c2bf20_1
  - idna=2.8=py36_0
  - imageio=2.5.0=py36_0
  - intel-openmp=2019.4=243
  - ipykernel=5.1.1=py36h39e3cac_0
  - ipython=7.1.1=py36h39e3cac_0
  - ipython_genutils=0.2.0=py36_0
  - ipywidgets=7.4.2=py36_0
  - jedi=0.13.3=py36_0
  - jinja2=2.10.1=py36_0
  - joblib=0.13.2=py36_0
  - jpeg=9b=h024ee3a_2
  - json-c=0.13.1=h1bed415_0
  - jsonschema=3.0.1=py36_0
  - jupyter=1.0.0=py36_7
  - jupyter_client=5.2.4=py36_0
  - jupyter_console=6.0.0=py36_0
  - jupyter_core=4.4.0=py36_0
  - kealib=1.4.7=h77bc034_6
  - kiwisolver=1.1.0=py36he6710b0_0
  - krb5=1.16.1=hc83ff2d_6
  - libboost=1.67.0=h46d08c1_4
  - libcurl=7.61.0=h1ad7b7a_0
  - libdap4=3.19.1=h6ec2957_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgdal=2.2.4=h6f639c0_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libkml=1.3.0=h590aaf7_4
  - libnetcdf=4.6.1=h10edf3e_1
  - libpng=1.6.37=hbc83047_0
  - libpq=10.5=h1ad7b7a_0
  - libsodium=1.0.16=h1bed415_0
  - libspatialindex=1.8.5=h20b78c2_2
  - libspatialite=4.3.0a=he475c7f_19
  - libssh2=1.8.0=h9cfc8f7_4
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.10=h2733197_2
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=he19cac6_0
  - libxslt=1.1.33=h7d1a2b0_0
  - llvmlite=0.28.0=py36hd408876_0
  - locket=0.2.0=py36_1
  - lxml=4.3.3=py36hefd8a0e_0
  - mapclassify=2.0.1=py_0
  - markdown=3.1.1=py36_0
  - markupsafe=1.1.1=py36h7b6447c_0
  - matplotlib=2.2.2=py36h0e671d2_1
  - mistune=0.8.4=py36h7b6447c_0
  - mkl=2019.4=243
  - mkl_fft=1.0.12=py36ha843d7b_0
  - mkl_random=1.0.2=py36hd81dba3_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.1=hdf1c602_3
  - msgpack-python=0.6.1=py36hfd86e86_1
  - multipledispatch=0.6.0=py36_0
  - munch=2.3.2=py36_0
  - nbconvert=5.5.0=py_0
  - nbformat=4.4.0=py36_0
  - ncurses=6.1=he6710b0_1
  - netcdf4=1.4.2=py36h4b4f87f_0
  - networkx=2.3=py_0
  - notebook=5.7.8=py36_0
  - numba=0.43.1=py36h962f231_0
  - numpy=1.16.4=py36h7e9f1db_0
  - numpy-base=1.16.4=py36hde5b4d6_0
  - olefile=0.46=py36_0
  - omp=1.0=0
  - openjpeg=2.3.0=h05c96fa_1
  - openssl=1.0.2s=h7b6447c_0
  - owslib=0.17.1=py_0
  - packaging=19.0=py36_0
  - pandas=0.24.2=py36he6710b0_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py36_1
  - panel=0.6.0=py_0
  - param=1.9.1=py_0
  - parso=0.4.0=py_0
  - partd=0.3.10=py36_1
  - pcre=8.43=he6710b0_0
  - pexpect=4.7.0=py36_0
  - phantomjs=2.1.1=0
  - pickleshare=0.7.5=py36_0
  - pillow=5.1.0=py36h3deb7b8_0
  - pip=19.1.1=py36_0
  - pixman=0.38.0=h7b6447c_0
  - plotly=3.10.0=py_0
  - poppler=0.65.0=ha54bb34_0
  - poppler-data=0.4.9=0
  - proj4=5.0.1=h14c3975_0
  - prometheus_client=0.6.0=py36_0
  - prompt_toolkit=2.0.9=py36_0
  - psutil=5.6.2=py36h7b6447c_0
  - psycopg2=2.7.5=py36hb7f436b_0
  - ptyprocess=0.6.0=py36_0
  - pycparser=2.19=py36_0
  - pyct=0.4.6=py_0
  - pyct-core=0.4.6=py_0
  - pyepsg=0.4.0=py36_0
  - pygments=2.4.2=py_0
  - pyopenssl=19.0.0=py36_0
  - pyparsing=2.4.0=py_0
  - pyproj=1.9.5.1=py36h7b21b82_1
  - pyqt=5.9.2=py36h751905a_0
  - pyrsistent=0.14.11=py36h7b6447c_0
  - pyshp=2.1.0=py_0
  - pysocks=1.7.0=py36_0
  - python=3.6.6=h6e4f718_2
  - python-dateutil=2.8.0=py36_0
  - python-snappy=0.5.4=py36he6710b0_0
  - pytz=2019.1=py_0
  - pyviz=0.10.0=py_0
  - pyviz_comms=0.7.2=py_0
  - pywavelets=1.0.3=py36hdd07704_1
  - pyyaml=5.1=py36h7b6447c_0
  - pyzmq=18.0.0=py36he6710b0_0
  - qt=5.9.5=h7e424d6_0
  - qtconsole=4.5.1=py_0
  - quspin=0.3.2=omp_py36hf4ba22b_0
  - readline=7.0=h7b6447c_5
  - requests=2.22.0=py36_0
  - retrying=1.3.3=py36_2
  - rise=5.3.0=py36_0
  - rtree=0.8.3=py36_0
  - scikit-image=0.15.0=py36he6710b0_0
  - scipy=1.2.1=py36h7c811a0_0
  - selenium=3.141.0=py36h7b6447c_0
  - send2trash=1.5.0=py36_0
  - setuptools=41.0.1=py36_0
  - shapely=1.6.4=py36h7ef4460_0
  - sip=4.19.8=py36hf484d3e_0
  - six=1.12.0=py36_0
  - snappy=1.1.7=hbae5bb6_3
  - sortedcontainers=2.1.0=py36_0
  - sqlalchemy=1.3.4=py36h7b6447c_0
  - sqlite=3.28.0=h7b6447c_0
  - streamz=0.5.1=py_0
  - tblib=1.4.0=py_0
  - terminado=0.8.2=py36_0
  - testpath=0.3.1=py36_0
  - thrift=0.11.0=py36hf484d3e_0
  - tk=8.6.8=hbc83047_0
  - toolz=0.9.0=py36_0
  - tornado=6.0.2=py36h7b6447c_0
  - traitlets=4.3.2=py36_0
  - urllib3=1.24.2=py36_0
  - wcwidth=0.1.7=py36_0
  - webencodings=0.5.1=py36_1
  - wheel=0.33.4=py36_0
  - widgetsnbextension=3.4.2=py36_0
  - xarray=0.11.3=py36_0
  - xerces-c=3.2.2=h780794e_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zeromq=4.3.1=he6710b0_3
  - zict=0.1.4=py36_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - colorama==0.4.1
    - tqdm==4.32.2
prefix: /media/maciejko/zhan/anaconda3/envs/quspin

